In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, inspect
import logging
import time

logging.basicConfig(
    filename="logs/ingestion_db.log",
    level=logging.DEBUG,
    format="%(asctime)s - %(levelname)s -%(message)s",
    filemode="a"
)

engine= create_engine("sqlite:///Inventoryy.db")
inspector= inspect(engine)

def ingest_db(df,tablename,engine):
    # this function() will ingest the dataframe to database table
    df.to_sql(tablename,con=engine,if_exists='replace',index= False)


def load_raw_data():
    # this function() will load the cvs as dataframe and ingest into db
    start= time.time()
    existing_tables = inspector.get_table_names()
    for file in os.listdir('data'):
         if '.csv' in file:
             table_name = file[:-4]
             if table_name in existing_tables:
                logging.info(f"Skipping {file} â€” already ingested.")
                continue
             try:
                 df= pd.read_csv('data/'+ file)
                 logging.info(f"Ingesting {file} in db")
                 ingest_db(df,table_name,engine)
             except Exception as e:
                logging.error(f"Failed to ingest {file}: {str(e)}")
    
    end= time.time()
    total_time=(end-start)/60
    logging.info("------Ingestion Complete------")
    logging.info(f"\n total time taken {total_time} minutes")         
             
if __name__ =="__main__":
    load_raw_data()

In [3]:
import pandas as pd

In [8]:
sales_df= pd.read_csv('data/sales.csv')
sales_df.head(5)

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [9]:
sales_df.shape

(12825363, 14)

In [6]:
import sqlite3

In [7]:
conn= sqlite3.connect("Inventoryy.db")

In [10]:
sales_df.to_sql("sales",conn,if_exists="append",index=False)

12825363

In [11]:
print(pd.read_sql("select count(*) from sales",conn))

   count(*)
0  12825363

In [13]:
display(pd.read_sql("select * from sales limit 5 ",conn))

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY